// Generated by stratus_hls 19.12-s100  (91710.131054)
// Mon Apr 26 03:14:08 2021
// from ../GauFilter.cpp
#include "GauFilter_rtl.h"

struct GauFilter;
GauFilter::GauFilter(sc_module_name name) : sc_module(name) 
    ,i_clk("i_clk")
    ,i_rst("i_rst")
    ,i_rgb_busy("i_rgb_busy")
    ,i_rgb_vld("i_rgb_vld")
    ,i_rgb_data("i_rgb_data")
    ,o_result_busy("o_result_busy")
    ,o_result_vld("o_result_vld")
    ,o_result_data("o_result_data")
    ,o_result_m_req_m_prev_trig_req("o_result_m_req_m_prev_trig_req")
    ,GauFilter_Xor_1Ux1U_1U_1_1_out1("GauFilter_Xor_1Ux1U_1U_1_1_out1")
    ,o_result_m_unacked_req("o_result_m_unacked_req")
    ,GauFilter_Or_1Ux1U_1U_4_2_out1("GauFilter_Or_1Ux1U_1U_4_2_out1")
    ,GauFilter_N_Muxb_1_2_16_4_4_out1("GauFilter_N_Muxb_1_2_16_4_4_out1")
    ,i_rgb_m_unvalidated_req("i_rgb_m_unvalidated_req")
    ,GauFilter_gen_busy_r_4_32_gen_busy_i_rgb_m_data_is_invalid_next("GauFilter_gen_busy_r_4_32_gen_busy_i_rgb_m_data_is_invalid_next")
    ,GauFilter_gen_busy_r_4_32_gdiv("GauFilter_gen_busy_r_4_32_gdiv")
    ,GauFilter_gen_busy_r_4_32_gnew_req("GauFilter_gen_busy_r_4_32_gnew_req")
    ,global_state_next("global_state_next")
    ,GauFilter_Add_8Ux8U_8U_4_24_out1("GauFilter_Add_8Ux8U_8U_4_24_out1")
    ,GauFilter_R11_4Mul2u8u8_4_23_out1("GauFilter_R11_4Mul2u8u8_4_23_out1")
    ,bits_001("bits_001")
    ,gs_ctrl4("gs_ctrl4")
    ,GauFilter_N_Mux_8_3_22_4_22_out1("GauFilter_N_Mux_8_3_22_4_22_out1")
    ,GauFilter_N_Mux_8_3_22_4_21_out1("GauFilter_N_Mux_8_3_22_4_21_out1")
    ,GauFilter_OrReduction_2U_1U_4_19_out1("GauFilter_OrReduction_2U_1U_4_19_out1")
    ,GauFilter_Eqi1u2_4_18_out1("GauFilter_Eqi1u2_4_18_out1")
    ,GauFilter_Eqi2u2_4_17_out1("GauFilter_Eqi2u2_4_17_out1")
    ,GauFilter_OrReduction_2U_1U_4_10_out1("GauFilter_OrReduction_2U_1U_4_10_out1")
    ,GauFilter_Eqi1u2_4_9_out1("GauFilter_Eqi1u2_4_9_out1")
    ,GauFilter_Eqi2u2_4_8_out1("GauFilter_Eqi2u2_4_8_out1")
    ,GauFilter_Eqi2u2_4_8_in1("GauFilter_Eqi2u2_4_8_in1")
    ,GauFilter_Add2i1u2_4_6_in1("GauFilter_Add2i1u2_4_6_in1")
    ,gs_ctrl0("gs_ctrl0")
    ,s_reg_34("s_reg_34")
    ,GauFilter_Add2u2Mul2i3u2_4_16_out1("GauFilter_Add2u2Mul2i3u2_4_16_out1")
    ,s_reg_33("s_reg_33")
    ,s_reg_32("s_reg_32")
    ,s_reg_31("s_reg_31")
    ,s_reg_30("s_reg_30")
    ,GauFilter_Add2i1u2_4_15_out1("GauFilter_Add2i1u2_4_15_out1")
    ,GauFilter_Add2i1u2_4_14_out1("GauFilter_Add2i1u2_4_14_out1")
    ,GauFilter_Add2i1u2_4_6_out1("GauFilter_Add2i1u2_4_6_out1")
    ,s_reg_28("s_reg_28")
    ,s_reg_29("s_reg_29")
    ,s_reg_27("s_reg_27")
    ,GauFilter_N_Mux_8_2_21_4_13_out1("GauFilter_N_Mux_8_2_21_4_13_out1")
    ,s_reg_26("s_reg_26")
    ,GauFilter_N_Mux_8_2_20_4_12_out1("GauFilter_N_Mux_8_2_20_4_12_out1")
    ,s_reg_25("s_reg_25")
    ,GauFilter_N_Mux_8_2_20_4_11_out1("GauFilter_N_Mux_8_2_20_4_11_out1")
    ,s_reg_24("s_reg_24")
    ,GauFilter_gen_busy_r_4_32_out1("GauFilter_gen_busy_r_4_32_out1")
    ,GauFilter_And_1Ux1U_1U_4_30_out1("GauFilter_And_1Ux1U_1U_4_30_out1")
    ,GauFilter_Not_1U_1U_1_3_out1("GauFilter_Not_1U_1U_1_3_out1")
    ,o_result_m_req_m_trig_req("o_result_m_req_m_trig_req")
    ,GauFilter_Lti3u2_4_28_out1("GauFilter_Lti3u2_4_28_out1")
    ,GauFilter_Lti3u2_4_29_out1("GauFilter_Lti3u2_4_29_out1")
    ,GauFilter_Add2i1u2_4_20_out1("GauFilter_Add2i1u2_4_20_out1")
    ,GauFilter_Lti3u2_4_7_out1("GauFilter_Lti3u2_4_7_out1")
    ,global_state("global_state")
    ,i_rgb_m_busy_req_0("i_rgb_m_busy_req_0")
    ,GauFilter_N_Mux_8_2_23_4_25_out1("GauFilter_N_Mux_8_2_23_4_25_out1")
    ,GauFilter_N_Mux_8_2_23_4_26_out1("GauFilter_N_Mux_8_2_23_4_26_out1")
    ,GauFilter_N_Mux_8_2_23_4_27_out1("GauFilter_N_Mux_8_2_23_4_27_out1")
    ,stall0("stall0")
    ,mask_in1("mask_in1")
    ,mask_out1("mask_out1")
{
  mask = new GauFilter_ROM_9X8_mask("mask");
  mask->in1(mask_in1);
  mask->out1(mask_out1);
  mask->clk(i_clk);

  SC_METHOD(drive_o_result_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_rgb_m_busy_req_0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_result_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_stall0);
  sensitive << ( global_state );
  sensitive << ( GauFilter_gen_busy_r_4_32_out1 );
  sensitive << ( GauFilter_And_1Ux1U_1U_4_30_out1 );

  SC_METHOD(drive_s_reg_24);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_25);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_26);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_27);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_28);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_29);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_30);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_31);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_32);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_33);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_34);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_GauFilter_Add2i1u2_4_6_in1);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_28 );

  SC_METHOD(GauFilter_Add2i1u2_4_6);
  sensitive << ( GauFilter_Add2i1u2_4_6_in1 );

  SC_METHOD(GauFilter_Lti3u2_4_7);
  sensitive << ( GauFilter_Add2i1u2_4_6_out1 );

  SC_METHOD(drive_GauFilter_Eqi2u2_4_8_in1);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_28 );

  SC_METHOD(GauFilter_Eqi2u2_4_8);
  sensitive << ( GauFilter_Eqi2u2_4_8_in1 );

  SC_METHOD(GauFilter_Eqi1u2_4_9);
  sensitive << ( GauFilter_Eqi2u2_4_8_in1 );

  SC_METHOD(GauFilter_OrReduction_2U_1U_4_10);
  sensitive << ( GauFilter_Eqi2u2_4_8_in1 );

  SC_METHOD(GauFilter_N_Mux_8_2_20_4_11);
  sensitive << ( GauFilter_Eqi2u2_4_8_out1 );
  sensitive << ( s_reg_24 );

  SC_METHOD(GauFilter_N_Mux_8_2_20_4_12);
  sensitive << ( GauFilter_Eqi1u2_4_9_out1 );
  sensitive << ( s_reg_25 );

  SC_METHOD(GauFilter_N_Mux_8_2_21_4_13);
  sensitive << ( GauFilter_OrReduction_2U_1U_4_10_out1 );
  sensitive << ( s_reg_26 );

  SC_METHOD(GauFilter_Add2i1u2_4_14);
  sensitive << ( s_reg_34 );

  SC_METHOD(GauFilter_Add2i1u2_4_15);
  sensitive << ( s_reg_27 );

  SC_METHOD(GauFilter_Add2u2Mul2i3u2_4_16);
  sensitive << ( s_reg_27 );
  sensitive << ( s_reg_34 );

  SC_METHOD(GauFilter_Eqi2u2_4_17);
  sensitive << ( s_reg_34 );

  SC_METHOD(GauFilter_Eqi1u2_4_18);
  sensitive << ( s_reg_34 );

  SC_METHOD(GauFilter_OrReduction_2U_1U_4_19);
  sensitive << ( s_reg_34 );

  SC_METHOD(GauFilter_Add2i1u2_4_20);
  sensitive << ( s_reg_34 );

  SC_METHOD(GauFilter_N_Mux_8_3_22_4_21);
  sensitive << ( s_reg_34 );
  sensitive << ( s_reg_32 );
  sensitive << ( s_reg_30 );
  sensitive << ( s_reg_31 );

  SC_METHOD(GauFilter_N_Mux_8_3_22_4_22);
  sensitive << ( s_reg_34 );
  sensitive << ( s_reg_24 );
  sensitive << ( s_reg_26 );
  sensitive << ( s_reg_25 );

  SC_METHOD(drive_mask_in1);
  sensitive << ( gs_ctrl4 );
  sensitive << ( s_reg_33 );
  sensitive << ( GauFilter_Add2u2Mul2i3u2_4_16_out1 );

  SC_METHOD(drive_bits_001);
  sensitive << ( mask_out1 );
  sensitive << ( GauFilter_N_Mux_8_3_22_4_21_out1 );

  SC_METHOD(GauFilter_R11_4Mul2u8u8_4_23);
  sensitive << ( bits_001 );

  SC_METHOD(GauFilter_Add_8Ux8U_8U_4_24);
  sensitive << ( GauFilter_R11_4Mul2u8u8_4_23_out1 );
  sensitive << ( GauFilter_N_Mux_8_3_22_4_22_out1 );

  SC_METHOD(GauFilter_N_Mux_8_2_23_4_25);
  sensitive << ( GauFilter_Eqi2u2_4_17_out1 );
  sensitive << ( GauFilter_Add_8Ux8U_8U_4_24_out1 );
  sensitive << ( s_reg_24 );

  SC_METHOD(GauFilter_N_Mux_8_2_23_4_26);
  sensitive << ( GauFilter_Eqi1u2_4_18_out1 );
  sensitive << ( GauFilter_Add_8Ux8U_8U_4_24_out1 );
  sensitive << ( s_reg_25 );

  SC_METHOD(GauFilter_N_Mux_8_2_23_4_27);
  sensitive << ( GauFilter_OrReduction_2U_1U_4_19_out1 );
  sensitive << ( s_reg_26 );
  sensitive << ( GauFilter_Add_8Ux8U_8U_4_24_out1 );

  SC_METHOD(GauFilter_Lti3u2_4_28);
  sensitive << ( s_reg_29 );

  SC_METHOD(GauFilter_Lti3u2_4_29);
  sensitive << ( s_reg_28 );

  SC_METHOD(drive_global_state);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_global_state_next);
  sensitive << ( global_state );
  sensitive << ( GauFilter_Lti3u2_4_7_out1 );
  sensitive << ( GauFilter_Add2i1u2_4_20_out1 );
  sensitive << ( GauFilter_Lti3u2_4_29_out1 );
  sensitive << ( GauFilter_Lti3u2_4_28_out1 );

  SC_METHOD(drive_gs_ctrl0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl4);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_rgb_busy);
  sensitive << ( GauFilter_gen_busy_r_4_32_out1 );

  SC_METHOD(GauFilter_gen_busy_r_4_32_p8);
  sensitive << ( GauFilter_gen_busy_r_4_32_gen_busy_i_rgb_m_data_is_invalid_next
   );
  sensitive << ( GauFilter_gen_busy_r_4_32_gdiv );
  sensitive << ( GauFilter_gen_busy_r_4_32_gnew_req );

  SC_METHOD(GauFilter_gen_busy_r_4_32_p7);
  sensitive << ( GauFilter_gen_busy_r_4_32_gdiv );

  SC_METHOD(GauFilter_gen_busy_r_4_32_p6);
  sensitive << ( GauFilter_gen_busy_r_4_32_gnew_req );
  sensitive << ( i_rgb_vld );

  SC_METHOD(GauFilter_gen_busy_r_4_32_p5);
  sensitive << ( i_rgb_vld );
  sensitive << ( i_rgb_m_unvalidated_req );
  sensitive << ( i_rgb_m_busy_req_0 );

  SC_METHOD(drive_i_rgb_m_unvalidated_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GauFilter_N_Muxb_1_2_16_4_4);
  sensitive << ( i_rgb_m_busy_req_0 );
  sensitive << ( i_rgb_m_unvalidated_req );
  sensitive << ( i_rgb_vld );

  SC_METHOD(drive_o_result_vld);
  sensitive << ( GauFilter_Or_1Ux1U_1U_4_2_out1 );

  SC_METHOD(GauFilter_Or_1Ux1U_1U_4_2);
  sensitive << ( GauFilter_Xor_1Ux1U_1U_1_1_out1 );
  sensitive << ( o_result_m_unacked_req );

  SC_METHOD(drive_o_result_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GauFilter_And_1Ux1U_1U_4_30);
  sensitive << ( o_result_vld );
  sensitive << ( o_result_busy );

  SC_METHOD(GauFilter_Xor_1Ux1U_1U_1_1);
  sensitive << ( o_result_m_req_m_prev_trig_req );
  sensitive << ( o_result_m_req_m_trig_req );

  SC_METHOD(drive_o_result_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GauFilter_Not_1U_1U_1_3);
  sensitive << ( o_result_m_req_m_trig_req );

}
// resource: regr_en_24
void GauFilter::drive_o_result_data(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    o_result_data = ( (sc_uint<24> )(sc_bv<24>)((sc_bv<8>)(
                    GauFilter_N_Mux_8_2_23_4_25_out1.read()), 
                    (sc_bv<16>)((sc_bv<8>)(GauFilter_N_Mux_8_2_23_4_26_out1
                    .read()), 
                    (sc_bv<8>)(GauFilter_N_Mux_8_2_23_4_27_out1.read()))) );
    break;
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_ss_1
void GauFilter::drive_i_rgb_m_busy_req_0(){
  if ( (i_rst.read() == 0ULL) ) {
    i_rgb_m_busy_req_0 = 1ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state.read()) ) {
      case 0ULL: case 1ULL: case 6ULL: 
        if ( GauFilter_Lti3u2_4_7_out1.read() );
        else {
          i_rgb_m_busy_req_0 = 0ULL;
        }
        break;
      case 2ULL: 
        i_rgb_m_busy_req_0 = 1ULL;
        break;
      case 4ULL: 
        if ( (3ULL == GauFilter_Add2i1u2_4_20_out1.read()) ) {
          if ( GauFilter_Lti3u2_4_29_out1.read() ) {
            i_rgb_m_busy_req_0 = 0ULL;
          } else {
            if ( GauFilter_Lti3u2_4_28_out1.read() ) {
              i_rgb_m_busy_req_0 = 0ULL;
            } 
          }
        } 
        break;
      }
      break;
    }
  }
}
// resource: regr_en_sc_1
void GauFilter::drive_o_result_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_m_req_m_trig_req = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state.read()) ) {
      case 4ULL: 
        if ( ((3ULL == GauFilter_Add2i1u2_4_20_out1.read()) && (!
             GauFilter_Lti3u2_4_29_out1.read() && !GauFilter_Lti3u2_4_28_out1
             .read())) ) {
          o_result_m_req_m_trig_req = (sc_uint<1> ) (
                                      GauFilter_Not_1U_1U_1_3_out1.read());
        } 
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx3i1c
void GauFilter::drive_stall0(){
  switch( (sc_uint<3>)(global_state.read()) ) {
  default:
    stall0 = 0ULL;
    break;
  case 2ULL: 
    stall0 = (sc_uint<1> )GauFilter_gen_busy_r_4_32_out1.read();
    break;
  case 5ULL: 
    stall0 = GauFilter_And_1Ux1U_1U_4_30_out1.read();
    break;
  }
}
// resource: mux_8bx2i0c
// resource: regr_en_sc_8
void GauFilter::drive_s_reg_24(){
  if ( (i_rst.read() == 0ULL) ) {
    s_reg_24 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state.read()) ) {
      case 0ULL: case 1ULL: case 6ULL: 
        s_reg_24 = GauFilter_N_Mux_8_2_20_4_11_out1.read();
        break;
      case 4ULL: 
        s_reg_24 = GauFilter_N_Mux_8_2_23_4_25_out1.read();
        break;
      }
      break;
    }
  }
}
// resource: mux_8bx2i0c
// resource: regr_en_sc_8
void GauFilter::drive_s_reg_25(){
  if ( (i_rst.read() == 0ULL) ) {
    s_reg_25 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state.read()) ) {
      case 0ULL: case 1ULL: case 6ULL: 
        s_reg_25 = GauFilter_N_Mux_8_2_20_4_12_out1.read();
        break;
      case 4ULL: 
        s_reg_25 = GauFilter_N_Mux_8_2_23_4_26_out1.read();
        break;
      }
      break;
    }
  }
}
// resource: mux_8bx2i0c
// resource: regr_en_sc_8
void GauFilter::drive_s_reg_26(){
  if ( (i_rst.read() == 0ULL) ) {
    s_reg_26 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state.read()) ) {
      case 0ULL: case 1ULL: case 6ULL: 
        s_reg_26 = GauFilter_N_Mux_8_2_21_4_13_out1.read();
        break;
      case 4ULL: 
        s_reg_26 = GauFilter_N_Mux_8_2_23_4_27_out1.read();
        break;
      }
      break;
    }
  }
}
// resource: mux_2bx2i1c
// resource: regr_en_2
void GauFilter::drive_s_reg_27(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 0ULL: case 6ULL: 
      s_reg_27 = 0ULL;
      break;
    case 4ULL: 
      if ( (3ULL == GauFilter_Add2i1u2_4_20_out1.read()) ) {
        if ( GauFilter_Lti3u2_4_29_out1.read() );
        else {
          s_reg_27 = s_reg_29.read();
        }
      } 
      break;
    }
    break;
  }
}
// resource: mux_2bx2i0c
// resource: regr_en_2
void GauFilter::drive_s_reg_28(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 0ULL: case 1ULL: case 6ULL: 
      s_reg_28 = (sc_uint<2> ) (GauFilter_Add2i1u2_4_6_out1.read());
      break;
    case 2ULL: 
      s_reg_28 = (sc_uint<2> ) (GauFilter_Add2i1u2_4_14_out1.read());
      break;
    }
    break;
  }
}
// resource: regr_en_2
void GauFilter::drive_s_reg_29(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 2ULL: 
      s_reg_29 = (sc_uint<2> ) (GauFilter_Add2i1u2_4_15_out1.read());
      break;
    }
    break;
  }
}
// resource: regr_en_8
void GauFilter::drive_s_reg_30(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 2ULL: 
      s_reg_30 = (sc_uint<8> )i_rgb_data.read();
      break;
    }
    break;
  }
}
// resource: regr_en_8
void GauFilter::drive_s_reg_31(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 2ULL: 
      s_reg_31 = (sc_uint<8> ) (i_rgb_data.read().range(15,8));
      break;
    }
    break;
  }
}
// resource: regr_en_8
void GauFilter::drive_s_reg_32(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 2ULL: 
      s_reg_32 = (sc_uint<8> ) (i_rgb_data.read().range(23,16));
      break;
    }
    break;
  }
}
// resource: regr_en_4
void GauFilter::drive_s_reg_33(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 3ULL: 
      s_reg_33 = GauFilter_Add2u2Mul2i3u2_4_16_out1.read();
      break;
    }
    break;
  }
}
// resource: mux_2bx3i1c
// resource: regr_en_2
void GauFilter::drive_s_reg_34(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 0ULL: case 1ULL: case 3ULL: case 6ULL: 
      s_reg_34 = 0ULL;
      break;
    case 4ULL: 
      switch( (sc_uint<2>)(GauFilter_Add2i1u2_4_20_out1.read()) ) {
      default:
        s_reg_34 = (sc_uint<2> ) (GauFilter_Add2i1u2_4_20_out1.read());
        break;
      case 3ULL: 
        if ( GauFilter_Lti3u2_4_29_out1.read() ) {
          s_reg_34 = s_reg_28.read();
        } else {
          s_reg_34 = 0ULL;
        }
        break;
      }
      break;
    }
    break;
  }
}
// resource: mux_2bx2i1c
void GauFilter::drive_GauFilter_Add2i1u2_4_6_in1(){
  if ( gs_ctrl0.read() ) {
    GauFilter_Add2i1u2_4_6_in1 = (sc_uint<2> ) (s_reg_28.read());
  } else {
    GauFilter_Add2i1u2_4_6_in1 = 0ULL;
  }
}
// resource: GauFilter_Add2i1u2_4  instance: GauFilter_Add2i1u2_4_6
void GauFilter::GauFilter_Add2i1u2_4_6(){
  GauFilter_Add2i1u2_4_6_out1 = (/*cliff*/sc_uint<32>)(
                                GauFilter_Add2i1u2_4_6_in1.read() + 1ULL);
}
// resource: GauFilter_Lti3u2_4  instance: GauFilter_Lti3u2_4_7
void GauFilter::GauFilter_Lti3u2_4_7(){
  GauFilter_Lti3u2_4_7_out1 = (/*imp*/sc_uint<1>)(GauFilter_Add2i1u2_4_6_out1
                              .read() < (sc_uint<2> )3ULL);
}
// resource: mux_2bx2i1c
void GauFilter::drive_GauFilter_Eqi2u2_4_8_in1(){
  if ( gs_ctrl0.read() ) {
    GauFilter_Eqi2u2_4_8_in1 = s_reg_28.read();
  } else {
    GauFilter_Eqi2u2_4_8_in1 = 0ULL;
  }
}
// resource: GauFilter_Eqi2u2_4  instance: GauFilter_Eqi2u2_4_8
void GauFilter::GauFilter_Eqi2u2_4_8(){
  GauFilter_Eqi2u2_4_8_out1 = (GauFilter_Eqi2u2_4_8_in1.read() == 2ULL);
}
// resource: GauFilter_Eqi1u2_4  instance: GauFilter_Eqi1u2_4_9
void GauFilter::GauFilter_Eqi1u2_4_9(){
  GauFilter_Eqi1u2_4_9_out1 = (GauFilter_Eqi2u2_4_8_in1.read() == 1ULL);
}
// resource: GauFilter_OrReduction_2U_1U_4  instance: GauFilter_OrReduction_2U_1U_4_10
void GauFilter::GauFilter_OrReduction_2U_1U_4_10(){
  GauFilter_OrReduction_2U_1U_4_10_out1 = ((sc_uint<2>)GauFilter_Eqi2u2_4_8_in1
                                          .read()).or_reduce();
}
// resource: GauFilter_N_Mux_8_2_20_4
void GauFilter::GauFilter_N_Mux_8_2_20_4_11(){
  if ( GauFilter_Eqi2u2_4_8_out1.read() ) {
    GauFilter_N_Mux_8_2_20_4_11_out1 = 0ULL;
  } else {
    GauFilter_N_Mux_8_2_20_4_11_out1 = s_reg_24.read();
  }
}
// resource: GauFilter_N_Mux_8_2_20_4
void GauFilter::GauFilter_N_Mux_8_2_20_4_12(){
  if ( GauFilter_Eqi1u2_4_9_out1.read() ) {
    GauFilter_N_Mux_8_2_20_4_12_out1 = 0ULL;
  } else {
    GauFilter_N_Mux_8_2_20_4_12_out1 = s_reg_25.read();
  }
}
// resource: GauFilter_N_Mux_8_2_21_4
void GauFilter::GauFilter_N_Mux_8_2_21_4_13(){
  if ( GauFilter_OrReduction_2U_1U_4_10_out1.read() ) {
    GauFilter_N_Mux_8_2_21_4_13_out1 = s_reg_26.read();
  } else {
    GauFilter_N_Mux_8_2_21_4_13_out1 = 0ULL;
  }
}
// resource: GauFilter_Add2i1u2_4  instance: GauFilter_Add2i1u2_4_14
void GauFilter::GauFilter_Add2i1u2_4_14(){
  GauFilter_Add2i1u2_4_14_out1 = (/*cliff*/sc_uint<32>)((sc_uint<2> )s_reg_34
                                 .read() + 1ULL);
}
// resource: GauFilter_Add2i1u2_4  instance: GauFilter_Add2i1u2_4_15
void GauFilter::GauFilter_Add2i1u2_4_15(){
  GauFilter_Add2i1u2_4_15_out1 = (/*cliff*/sc_uint<32>)((sc_uint<2> )s_reg_27
                                 .read() + 1ULL);
}
// resource: GauFilter_Add2u2Mul2i3u2_4  instance: GauFilter_Add2u2Mul2i3u2_4_16
void GauFilter::GauFilter_Add2u2Mul2i3u2_4_16(){
  GauFilter_Add2u2Mul2i3u2_4_16_out1 = (s_reg_34.read() * 3ULL + s_reg_27.read()
                                       );
}
// resource: GauFilter_Eqi2u2_4  instance: GauFilter_Eqi2u2_4_17
void GauFilter::GauFilter_Eqi2u2_4_17(){
  GauFilter_Eqi2u2_4_17_out1 = (s_reg_34.read() == 2ULL);
}
// resource: GauFilter_Eqi1u2_4  instance: GauFilter_Eqi1u2_4_18
void GauFilter::GauFilter_Eqi1u2_4_18(){
  GauFilter_Eqi1u2_4_18_out1 = (s_reg_34.read() == 1ULL);
}
// resource: GauFilter_OrReduction_2U_1U_4  instance: GauFilter_OrReduction_2U_1U_4_19
void GauFilter::GauFilter_OrReduction_2U_1U_4_19(){
  GauFilter_OrReduction_2U_1U_4_19_out1 = ((sc_uint<2>)s_reg_34.read())
                                          .or_reduce();
}
// resource: GauFilter_Add2i1u2_4  instance: GauFilter_Add2i1u2_4_20
void GauFilter::GauFilter_Add2i1u2_4_20(){
  GauFilter_Add2i1u2_4_20_out1 = (/*cliff*/sc_uint<32>)((sc_uint<2> )s_reg_34
                                 .read() + 1ULL);
}
// resource: GauFilter_N_Mux_8_3_22_4
void GauFilter::GauFilter_N_Mux_8_3_22_4_21(){
  switch( (sc_uint<2>)(s_reg_34.read()) ) {
  default:
    GauFilter_N_Mux_8_3_22_4_21_out1 = s_reg_32.read();
    break;
  case 0ULL: 
    GauFilter_N_Mux_8_3_22_4_21_out1 = s_reg_30.read();
    break;
  case 1ULL: 
    GauFilter_N_Mux_8_3_22_4_21_out1 = s_reg_31.read();
    break;
  }
}
// resource: GauFilter_N_Mux_8_3_22_4
void GauFilter::GauFilter_N_Mux_8_3_22_4_22(){
  switch( (sc_uint<2>)(s_reg_34.read()) ) {
  default:
    GauFilter_N_Mux_8_3_22_4_22_out1 = s_reg_24.read();
    break;
  case 0ULL: 
    GauFilter_N_Mux_8_3_22_4_22_out1 = s_reg_26.read();
    break;
  case 1ULL: 
    GauFilter_N_Mux_8_3_22_4_22_out1 = s_reg_25.read();
    break;
  }
}
// resource: mux_4bx2i0c
void GauFilter::drive_mask_in1(){
  if ( gs_ctrl4.read() ) {
    mask_in1 = s_reg_33.read();
  } else {
    mask_in1 = GauFilter_Add2u2Mul2i3u2_4_16_out1.read();
  }
}
// resource: GauFilter_R11_4Mul2u8u8_4  instance: GauFilter_R11_4Mul2u8u8_4_23
void GauFilter::drive_bits_001(){
  bits_001 = GauFilter_N_Mux_8_3_22_4_21_out1.read() * mask_out1.read();
}
// resource: GauFilter_R11_4Mul2u8u8_4  instance: GauFilter_R11_4Mul2u8u8_4_23
void GauFilter::GauFilter_R11_4Mul2u8u8_4_23(){
  GauFilter_R11_4Mul2u8u8_4_23_out1 = (sc_uint<8> ) (bits_001.read().range(11,4)
                                      );
}
// resource: GauFilter_Add_8Ux8U_8U_4  instance: GauFilter_Add_8Ux8U_8U_4_24
void GauFilter::GauFilter_Add_8Ux8U_8U_4_24(){
  GauFilter_Add_8Ux8U_8U_4_24_out1 = (GauFilter_N_Mux_8_3_22_4_22_out1.read() + 
                                     GauFilter_R11_4Mul2u8u8_4_23_out1.read());
}
// resource: GauFilter_N_Mux_8_2_23_4
void GauFilter::GauFilter_N_Mux_8_2_23_4_25(){
  if ( GauFilter_Eqi2u2_4_17_out1.read() ) {
    GauFilter_N_Mux_8_2_23_4_25_out1 = GauFilter_Add_8Ux8U_8U_4_24_out1.read();
  } else {
    GauFilter_N_Mux_8_2_23_4_25_out1 = s_reg_24.read();
  }
}
// resource: GauFilter_N_Mux_8_2_23_4
void GauFilter::GauFilter_N_Mux_8_2_23_4_26(){
  if ( GauFilter_Eqi1u2_4_18_out1.read() ) {
    GauFilter_N_Mux_8_2_23_4_26_out1 = GauFilter_Add_8Ux8U_8U_4_24_out1.read();
  } else {
    GauFilter_N_Mux_8_2_23_4_26_out1 = s_reg_25.read();
  }
}
// resource: GauFilter_N_Mux_8_2_23_4
void GauFilter::GauFilter_N_Mux_8_2_23_4_27(){
  if ( GauFilter_OrReduction_2U_1U_4_19_out1.read() ) {
    GauFilter_N_Mux_8_2_23_4_27_out1 = s_reg_26.read();
  } else {
    GauFilter_N_Mux_8_2_23_4_27_out1 = GauFilter_Add_8Ux8U_8U_4_24_out1.read();
  }
}
// resource: GauFilter_Lti3u2_4  instance: GauFilter_Lti3u2_4_28
void GauFilter::GauFilter_Lti3u2_4_28(){
  GauFilter_Lti3u2_4_28_out1 = (/*imp*/sc_uint<1>)((sc_uint<2> )s_reg_29.read()
                                < (sc_uint<2> )3ULL);
}
// resource: GauFilter_Lti3u2_4  instance: GauFilter_Lti3u2_4_29
void GauFilter::GauFilter_Lti3u2_4_29(){
  GauFilter_Lti3u2_4_29_out1 = (/*imp*/sc_uint<1>)((sc_uint<2> )s_reg_28.read()
                                < (sc_uint<2> )3ULL);
}
// resource: regr_en_sc_3
void GauFilter::drive_global_state(){
  if ( (i_rst.read() == 0ULL) ) {
    global_state = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      global_state = global_state_next.read();
      break;
    }
  }
}
// resource: mux_3bx4i3c
void GauFilter::drive_global_state_next(){
  switch( (sc_uint<3>)(global_state.read()) ) {
  default:
    global_state_next = (global_state.read() + 1ULL);
    break;
  case 0ULL: case 1ULL: case 6ULL: 
    if ( GauFilter_Lti3u2_4_7_out1.read() ) {
      global_state_next = 1ULL;
    } else {
      global_state_next = 2ULL;
    }
    break;
  case 4ULL: 
    switch( (sc_uint<2>)(GauFilter_Add2i1u2_4_20_out1.read()) ) {
    default:
      global_state_next = 4ULL;
      break;
    case 3ULL: 
      if ( GauFilter_Lti3u2_4_29_out1.read() ) {
        global_state_next = 2ULL;
      } else {
        if ( GauFilter_Lti3u2_4_28_out1.read() ) {
          global_state_next = 2ULL;
        } else {
          global_state_next = (global_state.read() + 1ULL);
        }
      }
      break;
    }
    break;
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_sc_1
void GauFilter::drive_gs_ctrl0(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl0 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state_next.read()) ) {
      default:
        gs_ctrl0 = 0ULL;
        break;
      case 1ULL: 
        gs_ctrl0 = 1ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_sc_1
void GauFilter::drive_gs_ctrl4(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl4 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state_next.read()) ) {
      default:
        gs_ctrl4 = 0ULL;
        break;
      case 4ULL: 
        gs_ctrl4 = 1ULL;
        break;
      }
      break;
    }
  }
}
void GauFilter::drive_i_rgb_busy(){
  i_rgb_busy = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) 
               GauFilter_gen_busy_r_4_32_out1.read().range(2,2)));
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_32
void GauFilter::GauFilter_gen_busy_r_4_32_p8(){
  GauFilter_gen_busy_r_4_32_out1 = (sc_uint<3> ) (( (sc_biguint<3> )(sc_bv<3>)(
                                   (sc_bv<1>)(GauFilter_gen_busy_r_4_32_gnew_req
                                   .read()), 
                                   (sc_bv<2>)(( (sc_biguint<2> )(sc_bv<2>)(
                                   (sc_bv<1>)(GauFilter_gen_busy_r_4_32_gdiv
                                   .read()), 
                                   (sc_bv<1>)(GauFilter_gen_busy_r_4_32_gen_busy_i_rgb_m_data_is_invalid_next
                                   .read())) ))) ));
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_32
void GauFilter::GauFilter_gen_busy_r_4_32_p7(){
  GauFilter_gen_busy_r_4_32_gen_busy_i_rgb_m_data_is_invalid_next = ~(
                                                                    sc_uint<1>)GauFilter_gen_busy_r_4_32_gdiv
                                                                    .read();
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_32
void GauFilter::GauFilter_gen_busy_r_4_32_p6(){
  GauFilter_gen_busy_r_4_32_gdiv = (sc_uint<1> ) (i_rgb_vld.read() & !
                                   GauFilter_gen_busy_r_4_32_gnew_req.read());
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_32
void GauFilter::GauFilter_gen_busy_r_4_32_p5(){
  GauFilter_gen_busy_r_4_32_gnew_req = (sc_uint<1> ) (i_rgb_m_busy_req_0.read()
                                        & ( i_rgb_m_unvalidated_req.read() | (
                                       sc_uint<1> )i_rgb_vld.read() ));
}
// resource: regr_ss_1
void GauFilter::drive_i_rgb_m_unvalidated_req(){
  if ( (i_rst.read() == 0ULL) ) {
    i_rgb_m_unvalidated_req = 1ULL;
  } else {
    i_rgb_m_unvalidated_req = (sc_uint<1> ) (GauFilter_N_Muxb_1_2_16_4_4_out1
                              .read());
  }
}
// resource: GauFilter_N_Muxb_1_2_16_4
void GauFilter::GauFilter_N_Muxb_1_2_16_4_4(){
  if ( i_rgb_m_busy_req_0.read() ) {
    GauFilter_N_Muxb_1_2_16_4_4_out1 = (sc_uint<1> ) (i_rgb_m_unvalidated_req
                                       .read());
  } else {
    GauFilter_N_Muxb_1_2_16_4_4_out1 = (sc_uint<1> ) (i_rgb_vld.read());
  }
}
void GauFilter::drive_o_result_vld(){
  o_result_vld = (sc_uint<1> ) (GauFilter_Or_1Ux1U_1U_4_2_out1.read());
}
// resource: GauFilter_Or_1Ux1U_1U_4  instance: GauFilter_Or_1Ux1U_1U_4_2
void GauFilter::GauFilter_Or_1Ux1U_1U_4_2(){
  GauFilter_Or_1Ux1U_1U_4_2_out1 = (sc_uint<1> ) (o_result_m_unacked_req.read()
                                    | (sc_uint<1>)
                                   GauFilter_Xor_1Ux1U_1U_1_1_out1.read());
}
// resource: regr_sc_1
void GauFilter::drive_o_result_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_m_unacked_req = 0ULL;
  } else {
    o_result_m_unacked_req = (sc_uint<1> ) (GauFilter_And_1Ux1U_1U_4_30_out1
                             .read());
  }
}
// resource: GauFilter_And_1Ux1U_1U_4  instance: GauFilter_And_1Ux1U_1U_4_30
void GauFilter::GauFilter_And_1Ux1U_1U_4_30(){
  GauFilter_And_1Ux1U_1U_4_30_out1 = (sc_uint<1> ) (o_result_busy.read() & 
                                     o_result_vld.read());
}
// resource: GauFilter_Xor_1Ux1U_1U_1  instance: GauFilter_Xor_1Ux1U_1U_1_1
void GauFilter::GauFilter_Xor_1Ux1U_1U_1_1(){
  GauFilter_Xor_1Ux1U_1U_1_1_out1 = (sc_uint<1> ) (o_result_m_req_m_trig_req
                                    .read() ^ o_result_m_req_m_prev_trig_req
                                    .read());
}
// resource: regr_sc_1
void GauFilter::drive_o_result_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_result_m_req_m_prev_trig_req = o_result_m_req_m_trig_req.read();
  }
}
// resource: GauFilter_Not_1U_1U_1  instance: GauFilter_Not_1U_1U_1_3
void GauFilter::GauFilter_Not_1U_1U_1_3(){
  GauFilter_Not_1U_1U_1_3_out1 = !o_result_m_req_m_trig_req.read();
}
