`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 26 2021 03:10:21 CST (Apr 25 2021 19:10:21 UTC)

module GauFilter_Or_1Ux1U_1U_4(in2, in1, out1);
  input in2, in1;
  output out1;
  wire in2, in1;
  wire out1;
  OR2XL g2(.A (in2), .B (in1), .Y (out1));
endmodule


