// Generated by stratus_hls 19.12-s100  (91710.131054)
// Mon Apr 26 03:10:49 2021
// from ../GauFilter.cpp

`timescale 1ps / 1ps

      
module GauFilter_ROM_9X8_mask(in1, out1, clk);

      input [3:0] in1;
      input clk;
      output [7:0] out1;
      reg [7:0] out1;
      reg[7:0] mask[8:0];

         initial begin
            $readmemh("bdw_work/modules/GauFilter/BASIC/GauFilter_ROM_9X8_mask_0.memh", mask);
         end

         always @(posedge clk)
          begin :GauFilter_ROM_9X8_mask_mask_thread_1
            if (in1 < 4'd09) begin
               out1 <= mask[in1];
            end
         end


endmodule

