// Generated by stratus_hls 19.12-s100  (91710.131054)
// Mon Apr 26 02:59:59 2021
// from ../GauFilter.cpp
#include "GauFilter_rtl.h"

struct GauFilter;
GauFilter::GauFilter(sc_module_name name) : sc_module(name) 
    ,i_clk("i_clk")
    ,i_rst("i_rst")
    ,i_r_busy("i_r_busy")
    ,i_r_vld("i_r_vld")
    ,i_r_data("i_r_data")
    ,i_g_busy("i_g_busy")
    ,i_g_vld("i_g_vld")
    ,i_g_data("i_g_data")
    ,i_b_busy("i_b_busy")
    ,i_b_vld("i_b_vld")
    ,i_b_data("i_b_data")
    ,o_result_busy("o_result_busy")
    ,o_result_vld("o_result_vld")
    ,o_result_data("o_result_data")
    ,o_result_m_req_m_prev_trig_req("o_result_m_req_m_prev_trig_req")
    ,GauFilter_Xor_1Ux1U_1U_1_1_out1("GauFilter_Xor_1Ux1U_1U_1_1_out1")
    ,o_result_m_unacked_req("o_result_m_unacked_req")
    ,GauFilter_Or_1Ux1U_1U_4_2_out1("GauFilter_Or_1Ux1U_1U_4_2_out1")
    ,GauFilter_N_Muxb_1_2_4_4_10_out1("GauFilter_N_Muxb_1_2_4_4_10_out1")
    ,i_b_m_unvalidated_req("i_b_m_unvalidated_req")
    ,GauFilter_gen_busy_r_4_41_gen_busy_0_i_r_m_data_is_invalid_next("GauFilter_gen_busy_r_4_41_gen_busy_0_i_r_m_data_is_invalid_next")
    ,GauFilter_gen_busy_r_4_41_gdiv_i3("GauFilter_gen_busy_r_4_41_gdiv_i3")
    ,GauFilter_gen_busy_r_4_41_gnew_req_i1("GauFilter_gen_busy_r_4_41_gnew_req_i1")
    ,GauFilter_N_Muxb_1_2_4_4_7_out1("GauFilter_N_Muxb_1_2_4_4_7_out1")
    ,i_g_m_unvalidated_req("i_g_m_unvalidated_req")
    ,GauFilter_gen_busy_r_4_40_gen_busy_0_i_r_m_data_is_invalid_next("GauFilter_gen_busy_r_4_40_gen_busy_0_i_r_m_data_is_invalid_next")
    ,GauFilter_gen_busy_r_4_40_gdiv_i3("GauFilter_gen_busy_r_4_40_gdiv_i3")
    ,GauFilter_gen_busy_r_4_40_gnew_req_i1("GauFilter_gen_busy_r_4_40_gnew_req_i1")
    ,GauFilter_N_Muxb_1_2_4_4_4_out1("GauFilter_N_Muxb_1_2_4_4_4_out1")
    ,i_r_m_unvalidated_req("i_r_m_unvalidated_req")
    ,GauFilter_gen_busy_r_4_39_gen_busy_0_i_r_m_data_is_invalid_next("GauFilter_gen_busy_r_4_39_gen_busy_0_i_r_m_data_is_invalid_next")
    ,GauFilter_gen_busy_r_4_39_gdiv_i3("GauFilter_gen_busy_r_4_39_gdiv_i3")
    ,GauFilter_gen_busy_r_4_39_gnew_req_i1("GauFilter_gen_busy_r_4_39_gnew_req_i1")
    ,global_state_next("global_state_next")
    ,GauFilter_Add_8Ux8U_8U_4_31_out1("GauFilter_Add_8Ux8U_8U_4_31_out1")
    ,GauFilter_Add_8Ux8U_8U_4_31_in1("GauFilter_Add_8Ux8U_8U_4_31_in1")
    ,GauFilter_Mul_8Ux8U_12U_4_30_out1("GauFilter_Mul_8Ux8U_12U_4_30_out1")
    ,gs_ctrl4("gs_ctrl4")
    ,GauFilter_N_Mux_8_3_2_4_29_out1("GauFilter_N_Mux_8_3_2_4_29_out1")
    ,GauFilter_N_Mux_8_3_2_4_28_out1("GauFilter_N_Mux_8_3_2_4_28_out1")
    ,GauFilter_OrReduction_2U_1U_4_26_out1("GauFilter_OrReduction_2U_1U_4_26_out1")
    ,GauFilter_Equal_2Ux1U_1U_4_25_out1("GauFilter_Equal_2Ux1U_1U_4_25_out1")
    ,GauFilter_OrReduction_2U_1U_4_16_out1("GauFilter_OrReduction_2U_1U_4_16_out1")
    ,GauFilter_Equal_2Ux1U_1U_4_15_out1("GauFilter_Equal_2Ux1U_1U_4_15_out1")
    ,GauFilter_Equal_2Ux1U_1U_4_15_in2("GauFilter_Equal_2Ux1U_1U_4_15_in2")
    ,GauFilter_Equal_2Ux2U_1U_4_14_out1("GauFilter_Equal_2Ux2U_1U_4_14_out1")
    ,GauFilter_Equal_2Ux2U_1U_4_14_in2("GauFilter_Equal_2Ux2U_1U_4_14_in2")
    ,gs_ctrl1("gs_ctrl1")
    ,GauFilter_Add_2Ux1U_2U_4_12_in2("GauFilter_Add_2Ux1U_2U_4_12_in2")
    ,gs_ctrl0("gs_ctrl0")
    ,GauFilter_Add_2Ux1U_2U_4_12_out1("GauFilter_Add_2Ux1U_2U_4_12_out1")
    ,s_reg_36("s_reg_36")
    ,s_reg_35("s_reg_35")
    ,GauFilter_Add_4Ux2U_4U_4_23_out1("GauFilter_Add_4Ux2U_4U_4_23_out1")
    ,GauFilter_Mul_2Ux2U_4U_4_22_out1("GauFilter_Mul_2Ux2U_4U_4_22_out1")
    ,s_reg_34("s_reg_34")
    ,s_reg_33("s_reg_33")
    ,s_reg_32("s_reg_32")
    ,GauFilter_Add_2Ux1U_2U_4_20_out1("GauFilter_Add_2Ux1U_2U_4_20_out1")
    ,GauFilter_Add_2Ux1U_2U_4_21_out1("GauFilter_Add_2Ux1U_2U_4_21_out1")
    ,s_reg_30("s_reg_30")
    ,s_reg_31("s_reg_31")
    ,s_reg_29("s_reg_29")
    ,GauFilter_N_Mux_8_2_1_4_19_out1("GauFilter_N_Mux_8_2_1_4_19_out1")
    ,s_reg_28("s_reg_28")
    ,GauFilter_N_Mux_8_2_0_4_18_out1("GauFilter_N_Mux_8_2_0_4_18_out1")
    ,s_reg_27("s_reg_27")
    ,GauFilter_N_Mux_8_2_0_4_17_out1("GauFilter_N_Mux_8_2_0_4_17_out1")
    ,s_reg_26("s_reg_26")
    ,GauFilter_gen_busy_r_4_39_out1("GauFilter_gen_busy_r_4_39_out1")
    ,GauFilter_gen_busy_r_4_40_out1("GauFilter_gen_busy_r_4_40_out1")
    ,GauFilter_gen_busy_r_4_41_out1("GauFilter_gen_busy_r_4_41_out1")
    ,GauFilter_And_1Ux1U_1U_4_37_out1("GauFilter_And_1Ux1U_1U_4_37_out1")
    ,GauFilter_Not_1U_1U_1_3_out1("GauFilter_Not_1U_1U_1_3_out1")
    ,o_result_m_req_m_trig_req("o_result_m_req_m_trig_req")
    ,i_b_m_busy_req_0("i_b_m_busy_req_0")
    ,i_g_m_busy_req_0("i_g_m_busy_req_0")
    ,GauFilter_LessThan_2Ux2U_1U_4_35_out1("GauFilter_LessThan_2Ux2U_1U_4_35_out1")
    ,GauFilter_LessThan_2Ux2U_1U_4_36_out1("GauFilter_LessThan_2Ux2U_1U_4_36_out1")
    ,GauFilter_Add_2Ux1U_2U_4_27_out1("GauFilter_Add_2Ux1U_2U_4_27_out1")
    ,GauFilter_LessThan_2Ux2U_1U_4_13_out1("GauFilter_LessThan_2Ux2U_1U_4_13_out1")
    ,global_state("global_state")
    ,i_r_m_busy_req_0("i_r_m_busy_req_0")
    ,GauFilter_N_Mux_8_2_3_4_32_out1("GauFilter_N_Mux_8_2_3_4_32_out1")
    ,GauFilter_N_Mux_8_2_3_4_33_out1("GauFilter_N_Mux_8_2_3_4_33_out1")
    ,GauFilter_N_Mux_8_2_3_4_34_out1("GauFilter_N_Mux_8_2_3_4_34_out1")
    ,stall0("stall0")
    ,mask_in1("mask_in1")
    ,mask_out1("mask_out1")
{
  mask = new GauFilter_ROM_9X8_mask("mask");
  mask->in1(mask_in1);
  mask->out1(mask_out1);
  mask->clk(i_clk);

  SC_METHOD(drive_o_result_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_r_m_busy_req_0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_g_m_busy_req_0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_b_m_busy_req_0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_result_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_stall0);
  sensitive << ( global_state );
  sensitive << ( GauFilter_gen_busy_r_4_39_out1 );
  sensitive << ( GauFilter_gen_busy_r_4_40_out1 );
  sensitive << ( GauFilter_gen_busy_r_4_41_out1 );
  sensitive << ( GauFilter_And_1Ux1U_1U_4_37_out1 );

  SC_METHOD(drive_s_reg_26);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_27);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_28);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_29);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_30);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_31);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_32);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_33);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_34);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_35);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_36);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_GauFilter_Add_2Ux1U_2U_4_12_in2);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_36 );

  SC_METHOD(GauFilter_Add_2Ux1U_2U_4_12);
  sensitive << ( GauFilter_Add_2Ux1U_2U_4_12_in2 );

  SC_METHOD(GauFilter_LessThan_2Ux2U_1U_4_13);
  sensitive << ( GauFilter_Add_2Ux1U_2U_4_12_out1 );

  SC_METHOD(drive_GauFilter_Equal_2Ux2U_1U_4_14_in2);
  sensitive << ( gs_ctrl1 );
  sensitive << ( s_reg_36 );

  SC_METHOD(GauFilter_Equal_2Ux2U_1U_4_14);
  sensitive << ( GauFilter_Equal_2Ux2U_1U_4_14_in2 );

  SC_METHOD(drive_GauFilter_Equal_2Ux1U_1U_4_15_in2);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_36 );

  SC_METHOD(GauFilter_Equal_2Ux1U_1U_4_15);
  sensitive << ( GauFilter_Equal_2Ux1U_1U_4_15_in2 );

  SC_METHOD(GauFilter_OrReduction_2U_1U_4_16);
  sensitive << ( GauFilter_Equal_2Ux1U_1U_4_15_in2 );

  SC_METHOD(GauFilter_N_Mux_8_2_0_4_17);
  sensitive << ( GauFilter_Equal_2Ux2U_1U_4_14_out1 );
  sensitive << ( s_reg_26 );

  SC_METHOD(GauFilter_N_Mux_8_2_0_4_18);
  sensitive << ( GauFilter_Equal_2Ux1U_1U_4_15_out1 );
  sensitive << ( s_reg_27 );

  SC_METHOD(GauFilter_N_Mux_8_2_1_4_19);
  sensitive << ( GauFilter_OrReduction_2U_1U_4_16_out1 );
  sensitive << ( s_reg_28 );

  SC_METHOD(GauFilter_Add_2Ux1U_2U_4_20);
  sensitive << ( s_reg_29 );

  SC_METHOD(GauFilter_Add_2Ux1U_2U_4_21);
  sensitive << ( s_reg_30 );

  SC_METHOD(GauFilter_Mul_2Ux2U_4U_4_22);
  sensitive << ( s_reg_30 );

  SC_METHOD(GauFilter_Add_4Ux2U_4U_4_23);
  sensitive << ( s_reg_29 );
  sensitive << ( s_reg_34 );

  SC_METHOD(GauFilter_Equal_2Ux1U_1U_4_25);
  sensitive << ( s_reg_36 );

  SC_METHOD(GauFilter_OrReduction_2U_1U_4_26);
  sensitive << ( s_reg_36 );

  SC_METHOD(GauFilter_Add_2Ux1U_2U_4_27);
  sensitive << ( s_reg_36 );

  SC_METHOD(GauFilter_N_Mux_8_3_2_4_28);
  sensitive << ( s_reg_36 );
  sensitive << ( s_reg_35 );
  sensitive << ( s_reg_32 );
  sensitive << ( s_reg_33 );

  SC_METHOD(GauFilter_N_Mux_8_3_2_4_29);
  sensitive << ( s_reg_36 );
  sensitive << ( s_reg_26 );
  sensitive << ( s_reg_28 );
  sensitive << ( s_reg_27 );

  SC_METHOD(drive_mask_in1);
  sensitive << ( gs_ctrl4 );
  sensitive << ( s_reg_34 );
  sensitive << ( GauFilter_Add_4Ux2U_4U_4_23_out1 );

  SC_METHOD(GauFilter_Mul_8Ux8U_12U_4_30);
  sensitive << ( mask_out1 );
  sensitive << ( GauFilter_N_Mux_8_3_2_4_28_out1 );

  SC_METHOD(drive_GauFilter_Add_8Ux8U_8U_4_31_in1);
  sensitive << ( GauFilter_Mul_8Ux8U_12U_4_30_out1 );

  SC_METHOD(GauFilter_Add_8Ux8U_8U_4_31);
  sensitive << ( GauFilter_Add_8Ux8U_8U_4_31_in1 );
  sensitive << ( GauFilter_N_Mux_8_3_2_4_29_out1 );

  SC_METHOD(GauFilter_N_Mux_8_2_3_4_32);
  sensitive << ( GauFilter_Equal_2Ux2U_1U_4_14_out1 );
  sensitive << ( GauFilter_Add_8Ux8U_8U_4_31_out1 );
  sensitive << ( s_reg_26 );

  SC_METHOD(GauFilter_N_Mux_8_2_3_4_33);
  sensitive << ( GauFilter_Equal_2Ux1U_1U_4_25_out1 );
  sensitive << ( GauFilter_Add_8Ux8U_8U_4_31_out1 );
  sensitive << ( s_reg_27 );

  SC_METHOD(GauFilter_N_Mux_8_2_3_4_34);
  sensitive << ( GauFilter_OrReduction_2U_1U_4_26_out1 );
  sensitive << ( s_reg_28 );
  sensitive << ( GauFilter_Add_8Ux8U_8U_4_31_out1 );

  SC_METHOD(GauFilter_LessThan_2Ux2U_1U_4_35);
  sensitive << ( s_reg_31 );

  SC_METHOD(GauFilter_LessThan_2Ux2U_1U_4_36);
  sensitive << ( s_reg_30 );

  SC_METHOD(drive_global_state);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_global_state_next);
  sensitive << ( global_state );
  sensitive << ( GauFilter_LessThan_2Ux2U_1U_4_13_out1 );
  sensitive << ( GauFilter_Add_2Ux1U_2U_4_27_out1 );
  sensitive << ( GauFilter_LessThan_2Ux2U_1U_4_36_out1 );
  sensitive << ( GauFilter_LessThan_2Ux2U_1U_4_35_out1 );

  SC_METHOD(drive_gs_ctrl0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl1);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl4);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_r_busy);
  sensitive << ( GauFilter_gen_busy_r_4_39_out1 );

  SC_METHOD(GauFilter_gen_busy_r_4_39_p8);
  sensitive << ( GauFilter_gen_busy_r_4_39_gen_busy_0_i_r_m_data_is_invalid_next
   );
  sensitive << ( GauFilter_gen_busy_r_4_39_gdiv_i3 );
  sensitive << ( GauFilter_gen_busy_r_4_39_gnew_req_i1 );

  SC_METHOD(GauFilter_gen_busy_r_4_39_p7);
  sensitive << ( GauFilter_gen_busy_r_4_39_gdiv_i3 );

  SC_METHOD(GauFilter_gen_busy_r_4_39_p6);
  sensitive << ( GauFilter_gen_busy_r_4_39_gnew_req_i1 );
  sensitive << ( i_r_vld );

  SC_METHOD(GauFilter_gen_busy_r_4_39_p5);
  sensitive << ( i_r_vld );
  sensitive << ( i_r_m_unvalidated_req );
  sensitive << ( i_r_m_busy_req_0 );

  SC_METHOD(drive_i_r_m_unvalidated_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GauFilter_N_Muxb_1_2_4_4_4);
  sensitive << ( i_r_m_busy_req_0 );
  sensitive << ( i_r_m_unvalidated_req );
  sensitive << ( i_r_vld );

  SC_METHOD(drive_i_g_busy);
  sensitive << ( GauFilter_gen_busy_r_4_40_out1 );

  SC_METHOD(GauFilter_gen_busy_r_4_40_p8);
  sensitive << ( GauFilter_gen_busy_r_4_40_gen_busy_0_i_r_m_data_is_invalid_next
   );
  sensitive << ( GauFilter_gen_busy_r_4_40_gdiv_i3 );
  sensitive << ( GauFilter_gen_busy_r_4_40_gnew_req_i1 );

  SC_METHOD(GauFilter_gen_busy_r_4_40_p7);
  sensitive << ( GauFilter_gen_busy_r_4_40_gdiv_i3 );

  SC_METHOD(GauFilter_gen_busy_r_4_40_p6);
  sensitive << ( GauFilter_gen_busy_r_4_40_gnew_req_i1 );
  sensitive << ( i_g_vld );

  SC_METHOD(GauFilter_gen_busy_r_4_40_p5);
  sensitive << ( i_g_vld );
  sensitive << ( i_g_m_unvalidated_req );
  sensitive << ( i_g_m_busy_req_0 );

  SC_METHOD(drive_i_g_m_unvalidated_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GauFilter_N_Muxb_1_2_4_4_7);
  sensitive << ( i_g_m_busy_req_0 );
  sensitive << ( i_g_m_unvalidated_req );
  sensitive << ( i_g_vld );

  SC_METHOD(drive_i_b_busy);
  sensitive << ( GauFilter_gen_busy_r_4_41_out1 );

  SC_METHOD(GauFilter_gen_busy_r_4_41_p8);
  sensitive << ( GauFilter_gen_busy_r_4_41_gen_busy_0_i_r_m_data_is_invalid_next
   );
  sensitive << ( GauFilter_gen_busy_r_4_41_gdiv_i3 );
  sensitive << ( GauFilter_gen_busy_r_4_41_gnew_req_i1 );

  SC_METHOD(GauFilter_gen_busy_r_4_41_p7);
  sensitive << ( GauFilter_gen_busy_r_4_41_gdiv_i3 );

  SC_METHOD(GauFilter_gen_busy_r_4_41_p6);
  sensitive << ( GauFilter_gen_busy_r_4_41_gnew_req_i1 );
  sensitive << ( i_b_vld );

  SC_METHOD(GauFilter_gen_busy_r_4_41_p5);
  sensitive << ( i_b_vld );
  sensitive << ( i_b_m_unvalidated_req );
  sensitive << ( i_b_m_busy_req_0 );

  SC_METHOD(drive_i_b_m_unvalidated_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GauFilter_N_Muxb_1_2_4_4_10);
  sensitive << ( i_b_m_busy_req_0 );
  sensitive << ( i_b_m_unvalidated_req );
  sensitive << ( i_b_vld );

  SC_METHOD(drive_o_result_vld);
  sensitive << ( GauFilter_Or_1Ux1U_1U_4_2_out1 );

  SC_METHOD(GauFilter_Or_1Ux1U_1U_4_2);
  sensitive << ( GauFilter_Xor_1Ux1U_1U_1_1_out1 );
  sensitive << ( o_result_m_unacked_req );

  SC_METHOD(drive_o_result_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GauFilter_And_1Ux1U_1U_4_37);
  sensitive << ( o_result_vld );
  sensitive << ( o_result_busy );

  SC_METHOD(GauFilter_Xor_1Ux1U_1U_1_1);
  sensitive << ( o_result_m_req_m_prev_trig_req );
  sensitive << ( o_result_m_req_m_trig_req );

  SC_METHOD(drive_o_result_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GauFilter_Not_1U_1U_1_3);
  sensitive << ( o_result_m_req_m_trig_req );

}
// resource: regr_en_24
void GauFilter::drive_o_result_data(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    o_result_data = ( (sc_uint<24> )(sc_bv<24>)((sc_bv<8>)(
                    GauFilter_N_Mux_8_2_3_4_32_out1.read()), 
                    (sc_bv<16>)((sc_bv<8>)(GauFilter_N_Mux_8_2_3_4_33_out1
                    .read()), 
                    (sc_bv<8>)(GauFilter_N_Mux_8_2_3_4_34_out1.read()))) );
    break;
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_ss_1
void GauFilter::drive_i_r_m_busy_req_0(){
  if ( (i_rst.read() == 0ULL) ) {
    i_r_m_busy_req_0 = 1ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 0ULL: case 1ULL: case 8ULL: 
        if ( GauFilter_LessThan_2Ux2U_1U_4_13_out1.read() );
        else {
          i_r_m_busy_req_0 = 0ULL;
        }
        break;
      case 2ULL: 
        i_r_m_busy_req_0 = 1ULL;
        break;
      case 6ULL: 
        if ( (3ULL == GauFilter_Add_2Ux1U_2U_4_27_out1.read()) ) {
          if ( GauFilter_LessThan_2Ux2U_1U_4_36_out1.read() ) {
            i_r_m_busy_req_0 = 0ULL;
          } else {
            if ( GauFilter_LessThan_2Ux2U_1U_4_35_out1.read() ) {
              i_r_m_busy_req_0 = 0ULL;
            } 
          }
        } 
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_ss_1
void GauFilter::drive_i_g_m_busy_req_0(){
  if ( (i_rst.read() == 0ULL) ) {
    i_g_m_busy_req_0 = 1ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 2ULL: 
        i_g_m_busy_req_0 = 0ULL;
        break;
      case 3ULL: 
        i_g_m_busy_req_0 = 1ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_ss_1
void GauFilter::drive_i_b_m_busy_req_0(){
  if ( (i_rst.read() == 0ULL) ) {
    i_b_m_busy_req_0 = 1ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 3ULL: 
        i_b_m_busy_req_0 = 0ULL;
        break;
      case 4ULL: 
        i_b_m_busy_req_0 = 1ULL;
        break;
      }
      break;
    }
  }
}
// resource: regr_en_sc_1
void GauFilter::drive_o_result_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_m_req_m_trig_req = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 6ULL: 
        if ( ((3ULL == GauFilter_Add_2Ux1U_2U_4_27_out1.read()) && (!
             GauFilter_LessThan_2Ux2U_1U_4_36_out1.read() && !
             GauFilter_LessThan_2Ux2U_1U_4_35_out1.read())) ) {
          o_result_m_req_m_trig_req = (sc_uint<1> ) (
                                      GauFilter_Not_1U_1U_1_3_out1.read());
        } 
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx5i1c
void GauFilter::drive_stall0(){
  switch( (sc_uint<4>)(global_state.read()) ) {
  default:
    stall0 = 0ULL;
    break;
  case 2ULL: 
    stall0 = (sc_uint<1> )GauFilter_gen_busy_r_4_39_out1.read();
    break;
  case 3ULL: 
    stall0 = (sc_uint<1> )GauFilter_gen_busy_r_4_40_out1.read();
    break;
  case 4ULL: 
    stall0 = (sc_uint<1> )GauFilter_gen_busy_r_4_41_out1.read();
    break;
  case 7ULL: 
    stall0 = GauFilter_And_1Ux1U_1U_4_37_out1.read();
    break;
  }
}
// resource: mux_8bx2i0c
// resource: regr_en_sc_8
void GauFilter::drive_s_reg_26(){
  if ( (i_rst.read() == 0ULL) ) {
    s_reg_26 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 0ULL: case 1ULL: case 8ULL: 
        s_reg_26 = GauFilter_N_Mux_8_2_0_4_17_out1.read();
        break;
      case 6ULL: 
        s_reg_26 = GauFilter_N_Mux_8_2_3_4_32_out1.read();
        break;
      }
      break;
    }
  }
}
// resource: mux_8bx2i0c
// resource: regr_en_sc_8
void GauFilter::drive_s_reg_27(){
  if ( (i_rst.read() == 0ULL) ) {
    s_reg_27 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 0ULL: case 1ULL: case 8ULL: 
        s_reg_27 = GauFilter_N_Mux_8_2_0_4_18_out1.read();
        break;
      case 6ULL: 
        s_reg_27 = GauFilter_N_Mux_8_2_3_4_33_out1.read();
        break;
      }
      break;
    }
  }
}
// resource: mux_8bx2i0c
// resource: regr_en_sc_8
void GauFilter::drive_s_reg_28(){
  if ( (i_rst.read() == 0ULL) ) {
    s_reg_28 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 0ULL: case 1ULL: case 8ULL: 
        s_reg_28 = GauFilter_N_Mux_8_2_1_4_19_out1.read();
        break;
      case 6ULL: 
        s_reg_28 = GauFilter_N_Mux_8_2_3_4_34_out1.read();
        break;
      }
      break;
    }
  }
}
// resource: mux_2bx2i1c
// resource: regr_en_2
void GauFilter::drive_s_reg_29(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 8ULL: 
      s_reg_29 = 0ULL;
      break;
    case 6ULL: 
      if ( (3ULL == GauFilter_Add_2Ux1U_2U_4_27_out1.read()) ) {
        if ( GauFilter_LessThan_2Ux2U_1U_4_36_out1.read() );
        else {
          s_reg_29 = s_reg_31.read();
        }
      } 
      break;
    }
    break;
  }
}
// resource: mux_2bx2i1c
// resource: regr_en_2
void GauFilter::drive_s_reg_30(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 1ULL: case 8ULL: 
      s_reg_30 = 0ULL;
      break;
    case 4ULL: 
      s_reg_30 = (sc_uint<2> ) (GauFilter_Add_2Ux1U_2U_4_21_out1.read());
      break;
    case 6ULL: 
      if ( (3ULL == GauFilter_Add_2Ux1U_2U_4_27_out1.read()) ) {
        if ( GauFilter_LessThan_2Ux2U_1U_4_36_out1.read() );
        else {
          s_reg_30 = 0ULL;
        }
      } 
      break;
    }
    break;
  }
}
// resource: regr_en_2
void GauFilter::drive_s_reg_31(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 2ULL: 
      s_reg_31 = (sc_uint<2> ) (GauFilter_Add_2Ux1U_2U_4_20_out1.read());
      break;
    }
    break;
  }
}
// resource: regr_en_8
void GauFilter::drive_s_reg_32(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 2ULL: 
      s_reg_32 = i_r_data.read();
      break;
    }
    break;
  }
}
// resource: regr_en_8
void GauFilter::drive_s_reg_33(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 3ULL: 
      s_reg_33 = i_g_data.read();
      break;
    }
    break;
  }
}
// resource: mux_4bx2i0c
// resource: regr_en_4
void GauFilter::drive_s_reg_34(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 4ULL: 
      s_reg_34 = GauFilter_Mul_2Ux2U_4U_4_22_out1.read();
      break;
    case 5ULL: 
      s_reg_34 = GauFilter_Add_4Ux2U_4U_4_23_out1.read();
      break;
    }
    break;
  }
}
// resource: regr_en_8
void GauFilter::drive_s_reg_35(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 4ULL: 
      s_reg_35 = i_b_data.read();
      break;
    }
    break;
  }
}
// resource: mux_2bx3i1c
// resource: regr_en_2
void GauFilter::drive_s_reg_36(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 1ULL: case 8ULL: 
      s_reg_36 = (sc_uint<2> ) (GauFilter_Add_2Ux1U_2U_4_12_out1.read());
      break;
    case 5ULL: 
      s_reg_36 = 0ULL;
      break;
    case 6ULL: 
      if ( (3ULL != GauFilter_Add_2Ux1U_2U_4_27_out1.read()) ) {
        s_reg_36 = (sc_uint<2> ) (GauFilter_Add_2Ux1U_2U_4_27_out1.read());
      } 
      break;
    }
    break;
  }
}
// resource: mux_2bx2i1c
void GauFilter::drive_GauFilter_Add_2Ux1U_2U_4_12_in2(){
  if ( gs_ctrl0.read() ) {
    GauFilter_Add_2Ux1U_2U_4_12_in2 = (sc_uint<2> ) (s_reg_36.read());
  } else {
    GauFilter_Add_2Ux1U_2U_4_12_in2 = 0ULL;
  }
}
// resource: GauFilter_Add_2Ux1U_2U_4  instance: GauFilter_Add_2Ux1U_2U_4_12
void GauFilter::GauFilter_Add_2Ux1U_2U_4_12(){
  GauFilter_Add_2Ux1U_2U_4_12_out1 = (/*cliff*/sc_uint<32>)(
                                     GauFilter_Add_2Ux1U_2U_4_12_in2.read() + 
                                     1ULL);
}
// resource: GauFilter_LessThan_2Ux2U_1U_4  instance: GauFilter_LessThan_2Ux2U_1U_4_13
void GauFilter::GauFilter_LessThan_2Ux2U_1U_4_13(){
  GauFilter_LessThan_2Ux2U_1U_4_13_out1 = (/*imp*/sc_uint<1>)(
                                          GauFilter_Add_2Ux1U_2U_4_12_out1
                                          .read() < (sc_uint<2> )3ULL);
}
// resource: mux_2bx2i1c
void GauFilter::drive_GauFilter_Equal_2Ux2U_1U_4_14_in2(){
  if ( gs_ctrl1.read() ) {
    GauFilter_Equal_2Ux2U_1U_4_14_in2 = s_reg_36.read();
  } else {
    GauFilter_Equal_2Ux2U_1U_4_14_in2 = 0ULL;
  }
}
// resource: GauFilter_Equal_2Ux2U_1U_4  instance: GauFilter_Equal_2Ux2U_1U_4_14
void GauFilter::GauFilter_Equal_2Ux2U_1U_4_14(){
  GauFilter_Equal_2Ux2U_1U_4_14_out1 = (GauFilter_Equal_2Ux2U_1U_4_14_in2.read()
                                        == 2ULL);
}
// resource: mux_2bx2i1c
void GauFilter::drive_GauFilter_Equal_2Ux1U_1U_4_15_in2(){
  if ( gs_ctrl0.read() ) {
    GauFilter_Equal_2Ux1U_1U_4_15_in2 = s_reg_36.read();
  } else {
    GauFilter_Equal_2Ux1U_1U_4_15_in2 = 0ULL;
  }
}
// resource: GauFilter_Equal_2Ux1U_1U_4  instance: GauFilter_Equal_2Ux1U_1U_4_15
void GauFilter::GauFilter_Equal_2Ux1U_1U_4_15(){
  GauFilter_Equal_2Ux1U_1U_4_15_out1 = (GauFilter_Equal_2Ux1U_1U_4_15_in2.read()
                                        == 1ULL);
}
// resource: GauFilter_OrReduction_2U_1U_4  instance: GauFilter_OrReduction_2U_1U_4_16
void GauFilter::GauFilter_OrReduction_2U_1U_4_16(){
  GauFilter_OrReduction_2U_1U_4_16_out1 = ((sc_uint<2>)
                                          GauFilter_Equal_2Ux1U_1U_4_15_in2
                                          .read()).or_reduce();
}
// resource: GauFilter_N_Mux_8_2_0_4
void GauFilter::GauFilter_N_Mux_8_2_0_4_17(){
  if ( GauFilter_Equal_2Ux2U_1U_4_14_out1.read() ) {
    GauFilter_N_Mux_8_2_0_4_17_out1 = 0ULL;
  } else {
    GauFilter_N_Mux_8_2_0_4_17_out1 = s_reg_26.read();
  }
}
// resource: GauFilter_N_Mux_8_2_0_4
void GauFilter::GauFilter_N_Mux_8_2_0_4_18(){
  if ( GauFilter_Equal_2Ux1U_1U_4_15_out1.read() ) {
    GauFilter_N_Mux_8_2_0_4_18_out1 = 0ULL;
  } else {
    GauFilter_N_Mux_8_2_0_4_18_out1 = s_reg_27.read();
  }
}
// resource: GauFilter_N_Mux_8_2_1_4
void GauFilter::GauFilter_N_Mux_8_2_1_4_19(){
  if ( GauFilter_OrReduction_2U_1U_4_16_out1.read() ) {
    GauFilter_N_Mux_8_2_1_4_19_out1 = s_reg_28.read();
  } else {
    GauFilter_N_Mux_8_2_1_4_19_out1 = 0ULL;
  }
}
// resource: GauFilter_Add_2Ux1U_2U_4  instance: GauFilter_Add_2Ux1U_2U_4_20
void GauFilter::GauFilter_Add_2Ux1U_2U_4_20(){
  GauFilter_Add_2Ux1U_2U_4_20_out1 = (/*cliff*/sc_uint<32>)((sc_uint<2> )
                                     s_reg_29.read() + 1ULL);
}
// resource: GauFilter_Add_2Ux1U_2U_4  instance: GauFilter_Add_2Ux1U_2U_4_21
void GauFilter::GauFilter_Add_2Ux1U_2U_4_21(){
  GauFilter_Add_2Ux1U_2U_4_21_out1 = (/*cliff*/sc_uint<32>)((sc_uint<2> )
                                     s_reg_30.read() + 1ULL);
}
// resource: GauFilter_Mul_2Ux2U_4U_4  instance: GauFilter_Mul_2Ux2U_4U_4_22
void GauFilter::GauFilter_Mul_2Ux2U_4U_4_22(){
  GauFilter_Mul_2Ux2U_4U_4_22_out1 = s_reg_30.read() * 3ULL;
}
// resource: GauFilter_Add_4Ux2U_4U_4  instance: GauFilter_Add_4Ux2U_4U_4_23
void GauFilter::GauFilter_Add_4Ux2U_4U_4_23(){
  GauFilter_Add_4Ux2U_4U_4_23_out1 = (s_reg_34.read() + s_reg_29.read());
}
// resource: GauFilter_Equal_2Ux1U_1U_4  instance: GauFilter_Equal_2Ux1U_1U_4_25
void GauFilter::GauFilter_Equal_2Ux1U_1U_4_25(){
  GauFilter_Equal_2Ux1U_1U_4_25_out1 = (s_reg_36.read() == 1ULL);
}
// resource: GauFilter_OrReduction_2U_1U_4  instance: GauFilter_OrReduction_2U_1U_4_26
void GauFilter::GauFilter_OrReduction_2U_1U_4_26(){
  GauFilter_OrReduction_2U_1U_4_26_out1 = ((sc_uint<2>)s_reg_36.read())
                                          .or_reduce();
}
// resource: GauFilter_Add_2Ux1U_2U_4  instance: GauFilter_Add_2Ux1U_2U_4_27
void GauFilter::GauFilter_Add_2Ux1U_2U_4_27(){
  GauFilter_Add_2Ux1U_2U_4_27_out1 = (/*cliff*/sc_uint<32>)((sc_uint<2> )
                                     s_reg_36.read() + 1ULL);
}
// resource: GauFilter_N_Mux_8_3_2_4
void GauFilter::GauFilter_N_Mux_8_3_2_4_28(){
  switch( (sc_uint<2>)(s_reg_36.read()) ) {
  default:
    GauFilter_N_Mux_8_3_2_4_28_out1 = s_reg_35.read();
    break;
  case 0ULL: 
    GauFilter_N_Mux_8_3_2_4_28_out1 = s_reg_32.read();
    break;
  case 1ULL: 
    GauFilter_N_Mux_8_3_2_4_28_out1 = s_reg_33.read();
    break;
  }
}
// resource: GauFilter_N_Mux_8_3_2_4
void GauFilter::GauFilter_N_Mux_8_3_2_4_29(){
  switch( (sc_uint<2>)(s_reg_36.read()) ) {
  default:
    GauFilter_N_Mux_8_3_2_4_29_out1 = s_reg_26.read();
    break;
  case 0ULL: 
    GauFilter_N_Mux_8_3_2_4_29_out1 = s_reg_28.read();
    break;
  case 1ULL: 
    GauFilter_N_Mux_8_3_2_4_29_out1 = s_reg_27.read();
    break;
  }
}
// resource: mux_4bx2i0c
void GauFilter::drive_mask_in1(){
  if ( gs_ctrl4.read() ) {
    mask_in1 = s_reg_34.read();
  } else {
    mask_in1 = GauFilter_Add_4Ux2U_4U_4_23_out1.read();
  }
}
// resource: GauFilter_Mul_8Ux8U_12U_4  instance: GauFilter_Mul_8Ux8U_12U_4_30
void GauFilter::GauFilter_Mul_8Ux8U_12U_4_30(){
  GauFilter_Mul_8Ux8U_12U_4_30_out1 = GauFilter_N_Mux_8_3_2_4_28_out1.read() * 
                                      mask_out1.read();
}
void GauFilter::drive_GauFilter_Add_8Ux8U_8U_4_31_in1(){
  GauFilter_Add_8Ux8U_8U_4_31_in1 = (sc_uint<8> ) (
                                    GauFilter_Mul_8Ux8U_12U_4_30_out1.read()
                                    .range(11,4));
}
// resource: GauFilter_Add_8Ux8U_8U_4  instance: GauFilter_Add_8Ux8U_8U_4_31
void GauFilter::GauFilter_Add_8Ux8U_8U_4_31(){
  GauFilter_Add_8Ux8U_8U_4_31_out1 = (GauFilter_N_Mux_8_3_2_4_29_out1.read() + 
                                     GauFilter_Add_8Ux8U_8U_4_31_in1.read());
}
// resource: GauFilter_N_Mux_8_2_3_4
void GauFilter::GauFilter_N_Mux_8_2_3_4_32(){
  if ( GauFilter_Equal_2Ux2U_1U_4_14_out1.read() ) {
    GauFilter_N_Mux_8_2_3_4_32_out1 = GauFilter_Add_8Ux8U_8U_4_31_out1.read();
  } else {
    GauFilter_N_Mux_8_2_3_4_32_out1 = s_reg_26.read();
  }
}
// resource: GauFilter_N_Mux_8_2_3_4
void GauFilter::GauFilter_N_Mux_8_2_3_4_33(){
  if ( GauFilter_Equal_2Ux1U_1U_4_25_out1.read() ) {
    GauFilter_N_Mux_8_2_3_4_33_out1 = GauFilter_Add_8Ux8U_8U_4_31_out1.read();
  } else {
    GauFilter_N_Mux_8_2_3_4_33_out1 = s_reg_27.read();
  }
}
// resource: GauFilter_N_Mux_8_2_3_4
void GauFilter::GauFilter_N_Mux_8_2_3_4_34(){
  if ( GauFilter_OrReduction_2U_1U_4_26_out1.read() ) {
    GauFilter_N_Mux_8_2_3_4_34_out1 = s_reg_28.read();
  } else {
    GauFilter_N_Mux_8_2_3_4_34_out1 = GauFilter_Add_8Ux8U_8U_4_31_out1.read();
  }
}
// resource: GauFilter_LessThan_2Ux2U_1U_4  instance: GauFilter_LessThan_2Ux2U_1U_4_35
void GauFilter::GauFilter_LessThan_2Ux2U_1U_4_35(){
  GauFilter_LessThan_2Ux2U_1U_4_35_out1 = (/*imp*/sc_uint<1>)((sc_uint<2> )
                                          s_reg_31.read() < (sc_uint<2> )3ULL);
}
// resource: GauFilter_LessThan_2Ux2U_1U_4  instance: GauFilter_LessThan_2Ux2U_1U_4_36
void GauFilter::GauFilter_LessThan_2Ux2U_1U_4_36(){
  GauFilter_LessThan_2Ux2U_1U_4_36_out1 = (/*imp*/sc_uint<1>)((sc_uint<2> )
                                          s_reg_30.read() < (sc_uint<2> )3ULL);
}
// resource: regr_en_sc_4
void GauFilter::drive_global_state(){
  if ( (i_rst.read() == 0ULL) ) {
    global_state = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      global_state = global_state_next.read();
      break;
    }
  }
}
// resource: mux_4bx4i3c
void GauFilter::drive_global_state_next(){
  switch( (sc_uint<4>)(global_state.read()) ) {
  default:
    global_state_next = (global_state.read() + 1ULL);
    break;
  case 0ULL: case 1ULL: case 8ULL: 
    if ( GauFilter_LessThan_2Ux2U_1U_4_13_out1.read() ) {
      global_state_next = 1ULL;
    } else {
      global_state_next = 2ULL;
    }
    break;
  case 6ULL: 
    switch( (sc_uint<2>)(GauFilter_Add_2Ux1U_2U_4_27_out1.read()) ) {
    default:
      global_state_next = 6ULL;
      break;
    case 3ULL: 
      if ( GauFilter_LessThan_2Ux2U_1U_4_36_out1.read() ) {
        global_state_next = 2ULL;
      } else {
        if ( GauFilter_LessThan_2Ux2U_1U_4_35_out1.read() ) {
          global_state_next = 2ULL;
        } else {
          global_state_next = (global_state.read() + 1ULL);
        }
      }
      break;
    }
    break;
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_sc_1
void GauFilter::drive_gs_ctrl0(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl0 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state_next.read()) ) {
      default:
        gs_ctrl0 = 0ULL;
        break;
      case 1ULL: 
        gs_ctrl0 = 1ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_sc_1
void GauFilter::drive_gs_ctrl1(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl1 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state_next.read()) ) {
      default:
        gs_ctrl1 = 0ULL;
        break;
      case 1ULL: case 6ULL: 
        gs_ctrl1 = 1ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_sc_1
void GauFilter::drive_gs_ctrl4(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl4 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state_next.read()) ) {
      default:
        gs_ctrl4 = 0ULL;
        break;
      case 6ULL: 
        gs_ctrl4 = 1ULL;
        break;
      }
      break;
    }
  }
}
void GauFilter::drive_i_r_busy(){
  i_r_busy = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) GauFilter_gen_busy_r_4_39_out1
             .read().range(2,2)));
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_39
void GauFilter::GauFilter_gen_busy_r_4_39_p8(){
  GauFilter_gen_busy_r_4_39_out1 = (sc_uint<3> ) (( (sc_biguint<3> )(sc_bv<3>)(
                                   (sc_bv<1>)(
                                   GauFilter_gen_busy_r_4_39_gnew_req_i1.read())
                                   , 
                                   (sc_bv<2>)(( (sc_biguint<2> )(sc_bv<2>)(
                                   (sc_bv<1>)(GauFilter_gen_busy_r_4_39_gdiv_i3
                                   .read()), 
                                   (sc_bv<1>)(GauFilter_gen_busy_r_4_39_gen_busy_0_i_r_m_data_is_invalid_next
                                   .read())) ))) ));
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_39
void GauFilter::GauFilter_gen_busy_r_4_39_p7(){
  GauFilter_gen_busy_r_4_39_gen_busy_0_i_r_m_data_is_invalid_next = ~(
                                                                    sc_uint<1>)GauFilter_gen_busy_r_4_39_gdiv_i3
                                                                    .read();
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_39
void GauFilter::GauFilter_gen_busy_r_4_39_p6(){
  GauFilter_gen_busy_r_4_39_gdiv_i3 = (sc_uint<1> ) (i_r_vld.read() & !
                                      GauFilter_gen_busy_r_4_39_gnew_req_i1
                                      .read());
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_39
void GauFilter::GauFilter_gen_busy_r_4_39_p5(){
  GauFilter_gen_busy_r_4_39_gnew_req_i1 = (sc_uint<1> ) (i_r_m_busy_req_0.read()
                                           & ( i_r_m_unvalidated_req.read() | (
                                          sc_uint<1> )i_r_vld.read() ));
}
// resource: regr_ss_1
void GauFilter::drive_i_r_m_unvalidated_req(){
  if ( (i_rst.read() == 0ULL) ) {
    i_r_m_unvalidated_req = 1ULL;
  } else {
    i_r_m_unvalidated_req = (sc_uint<1> ) (GauFilter_N_Muxb_1_2_4_4_4_out1
                            .read());
  }
}
// resource: GauFilter_N_Muxb_1_2_4_4
void GauFilter::GauFilter_N_Muxb_1_2_4_4_4(){
  if ( i_r_m_busy_req_0.read() ) {
    GauFilter_N_Muxb_1_2_4_4_4_out1 = (sc_uint<1> ) (i_r_m_unvalidated_req
                                      .read());
  } else {
    GauFilter_N_Muxb_1_2_4_4_4_out1 = (sc_uint<1> ) (i_r_vld.read());
  }
}
void GauFilter::drive_i_g_busy(){
  i_g_busy = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) GauFilter_gen_busy_r_4_40_out1
             .read().range(2,2)));
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_40
void GauFilter::GauFilter_gen_busy_r_4_40_p8(){
  GauFilter_gen_busy_r_4_40_out1 = (sc_uint<3> ) (( (sc_biguint<3> )(sc_bv<3>)(
                                   (sc_bv<1>)(
                                   GauFilter_gen_busy_r_4_40_gnew_req_i1.read())
                                   , 
                                   (sc_bv<2>)(( (sc_biguint<2> )(sc_bv<2>)(
                                   (sc_bv<1>)(GauFilter_gen_busy_r_4_40_gdiv_i3
                                   .read()), 
                                   (sc_bv<1>)(GauFilter_gen_busy_r_4_40_gen_busy_0_i_r_m_data_is_invalid_next
                                   .read())) ))) ));
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_40
void GauFilter::GauFilter_gen_busy_r_4_40_p7(){
  GauFilter_gen_busy_r_4_40_gen_busy_0_i_r_m_data_is_invalid_next = ~(
                                                                    sc_uint<1>)GauFilter_gen_busy_r_4_40_gdiv_i3
                                                                    .read();
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_40
void GauFilter::GauFilter_gen_busy_r_4_40_p6(){
  GauFilter_gen_busy_r_4_40_gdiv_i3 = (sc_uint<1> ) (i_g_vld.read() & !
                                      GauFilter_gen_busy_r_4_40_gnew_req_i1
                                      .read());
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_40
void GauFilter::GauFilter_gen_busy_r_4_40_p5(){
  GauFilter_gen_busy_r_4_40_gnew_req_i1 = (sc_uint<1> ) (i_g_m_busy_req_0.read()
                                           & ( i_g_m_unvalidated_req.read() | (
                                          sc_uint<1> )i_g_vld.read() ));
}
// resource: regr_ss_1
void GauFilter::drive_i_g_m_unvalidated_req(){
  if ( (i_rst.read() == 0ULL) ) {
    i_g_m_unvalidated_req = 1ULL;
  } else {
    i_g_m_unvalidated_req = (sc_uint<1> ) (GauFilter_N_Muxb_1_2_4_4_7_out1
                            .read());
  }
}
// resource: GauFilter_N_Muxb_1_2_4_4
void GauFilter::GauFilter_N_Muxb_1_2_4_4_7(){
  if ( i_g_m_busy_req_0.read() ) {
    GauFilter_N_Muxb_1_2_4_4_7_out1 = (sc_uint<1> ) (i_g_m_unvalidated_req
                                      .read());
  } else {
    GauFilter_N_Muxb_1_2_4_4_7_out1 = (sc_uint<1> ) (i_g_vld.read());
  }
}
void GauFilter::drive_i_b_busy(){
  i_b_busy = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) GauFilter_gen_busy_r_4_41_out1
             .read().range(2,2)));
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_41
void GauFilter::GauFilter_gen_busy_r_4_41_p8(){
  GauFilter_gen_busy_r_4_41_out1 = (sc_uint<3> ) (( (sc_biguint<3> )(sc_bv<3>)(
                                   (sc_bv<1>)(
                                   GauFilter_gen_busy_r_4_41_gnew_req_i1.read())
                                   , 
                                   (sc_bv<2>)(( (sc_biguint<2> )(sc_bv<2>)(
                                   (sc_bv<1>)(GauFilter_gen_busy_r_4_41_gdiv_i3
                                   .read()), 
                                   (sc_bv<1>)(GauFilter_gen_busy_r_4_41_gen_busy_0_i_r_m_data_is_invalid_next
                                   .read())) ))) ));
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_41
void GauFilter::GauFilter_gen_busy_r_4_41_p7(){
  GauFilter_gen_busy_r_4_41_gen_busy_0_i_r_m_data_is_invalid_next = ~(
                                                                    sc_uint<1>)GauFilter_gen_busy_r_4_41_gdiv_i3
                                                                    .read();
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_41
void GauFilter::GauFilter_gen_busy_r_4_41_p6(){
  GauFilter_gen_busy_r_4_41_gdiv_i3 = (sc_uint<1> ) (i_b_vld.read() & !
                                      GauFilter_gen_busy_r_4_41_gnew_req_i1
                                      .read());
}
// resource: GauFilter_gen_busy_r_4  instance: GauFilter_gen_busy_r_4_41
void GauFilter::GauFilter_gen_busy_r_4_41_p5(){
  GauFilter_gen_busy_r_4_41_gnew_req_i1 = (sc_uint<1> ) (i_b_m_busy_req_0.read()
                                           & ( i_b_m_unvalidated_req.read() | (
                                          sc_uint<1> )i_b_vld.read() ));
}
// resource: regr_ss_1
void GauFilter::drive_i_b_m_unvalidated_req(){
  if ( (i_rst.read() == 0ULL) ) {
    i_b_m_unvalidated_req = 1ULL;
  } else {
    i_b_m_unvalidated_req = (sc_uint<1> ) (GauFilter_N_Muxb_1_2_4_4_10_out1
                            .read());
  }
}
// resource: GauFilter_N_Muxb_1_2_4_4
void GauFilter::GauFilter_N_Muxb_1_2_4_4_10(){
  if ( i_b_m_busy_req_0.read() ) {
    GauFilter_N_Muxb_1_2_4_4_10_out1 = (sc_uint<1> ) (i_b_m_unvalidated_req
                                       .read());
  } else {
    GauFilter_N_Muxb_1_2_4_4_10_out1 = (sc_uint<1> ) (i_b_vld.read());
  }
}
void GauFilter::drive_o_result_vld(){
  o_result_vld = (sc_uint<1> ) (GauFilter_Or_1Ux1U_1U_4_2_out1.read());
}
// resource: GauFilter_Or_1Ux1U_1U_4  instance: GauFilter_Or_1Ux1U_1U_4_2
void GauFilter::GauFilter_Or_1Ux1U_1U_4_2(){
  GauFilter_Or_1Ux1U_1U_4_2_out1 = (sc_uint<1> ) (o_result_m_unacked_req.read()
                                    | (sc_uint<1>)
                                   GauFilter_Xor_1Ux1U_1U_1_1_out1.read());
}
// resource: regr_sc_1
void GauFilter::drive_o_result_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_m_unacked_req = 0ULL;
  } else {
    o_result_m_unacked_req = (sc_uint<1> ) (GauFilter_And_1Ux1U_1U_4_37_out1
                             .read());
  }
}
// resource: GauFilter_And_1Ux1U_1U_4  instance: GauFilter_And_1Ux1U_1U_4_37
void GauFilter::GauFilter_And_1Ux1U_1U_4_37(){
  GauFilter_And_1Ux1U_1U_4_37_out1 = (sc_uint<1> ) (o_result_busy.read() & 
                                     o_result_vld.read());
}
// resource: GauFilter_Xor_1Ux1U_1U_1  instance: GauFilter_Xor_1Ux1U_1U_1_1
void GauFilter::GauFilter_Xor_1Ux1U_1U_1_1(){
  GauFilter_Xor_1Ux1U_1U_1_1_out1 = (sc_uint<1> ) (o_result_m_req_m_trig_req
                                    .read() ^ o_result_m_req_m_prev_trig_req
                                    .read());
}
// resource: regr_sc_1
void GauFilter::drive_o_result_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_result_m_req_m_prev_trig_req = o_result_m_req_m_trig_req.read();
  }
}
// resource: GauFilter_Not_1U_1U_1  instance: GauFilter_Not_1U_1U_1_3
void GauFilter::GauFilter_Not_1U_1U_1_3(){
  GauFilter_Not_1U_1U_1_3_out1 = !o_result_m_req_m_trig_req.read();
}
