`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 26 2021 02:59:40 CST (Apr 25 2021 18:59:40 UTC)

module GauFilter_OrReduction_2U_1U_4(in1, out1);
  input [1:0] in1;
  output out1;
  wire [1:0] in1;
  wire out1;
  OR2XL g4(.A (in1[1]), .B (in1[0]), .Y (out1));
endmodule


